from django.urls import path
from . import views

urlpatterns = [
    path("api/lease", views.lease_view, name="lease_view"),
    path("api/lease/onboarding-documents", views.lease_onboarding_documents_view, name="lease_onboarding_documents"),
    path("api/lease/templates", views.get_templates, name="lease_get_templates"),
    path("api/lease/template-fields", views.get_template_fields, name="lease_get_template_fields"),
    path("api/lease/generate-contract", views.generate_contract, name="lease_generate_contract"),
    path("api/lease/send-negotiation", views.send_negotiation, name="lease_send_negotiation"),
    path("api/lease/send-invite", views.send_lease_invite, name="lease_send_invite"),
    path("api/lease/approval-otp",        views.lease_approval_otp,         name="lease_approval_otp"),
    path("api/lease/approval-otp-verify", views.lease_approval_verify_otp,  name="lease_approval_verify_otp"),
    path("api/lease/approve",             views.approve_lease_view,          name="approve_lease_view"),
    path("api/lease/cheques",             views.lease_cheque_view,            name="lease_cheque_view"),
    path("api/lease/cheque-status",       views.lease_cheque_status,          name="lease_cheque_status"),
    path("api/lease/all-cheques",         views.all_cheques_view,             name="all_cheques_view"),
    path("api/lease/cheque-summary",      views.cheque_summary_view,          name="cheque_summary_view"),
    path("api/lease/cheque-monthly",      views.cheque_monthly_view,          name="cheque_monthly_view"),
    path("api/lease/rent-analytics",      views.rent_analytics_view,          name="rent_analytics_view"),
    path("api/lease/property-analytics",  views.property_analytics_view,      name="property_analytics_view"),
    path("api/lease/property-comparison", views.property_comparison_view,     name="property_comparison_view"),
    path("api/lease/send-for-signature",  views.send_for_signature,           name="send_for_signature"),
    path("api/lease/signature-otp",       views.lease_signature_otp,          name="lease_signature_otp"),
    path("api/lease/signature-otp-verify",views.lease_signature_verify_otp,   name="lease_signature_verify_otp"),
    path("api/lease/submit-signature",    views.submit_lease_signature,       name="submit_lease_signature"),
    # Moved from property_management
    path('save/lease', views.lease_details_view, name='lease_details_view'),
    path('lease_documents', views.lease_documents, name='lease_documents'),
    path('lease/tenancy', views.lease_tenancy, name='lease_tenancy'),
    path('lease_tenancy_csv', views.export_lease_tenancy_csv, name='export_lease_tenancy_csv'),
    path('lease_pdf', views.lease_pdf_view, name='lease_pdf_view'),
    path('lease_term_and_condition', views.lease_term_and_condition, name='lease_term_and_condition'),
    path('property_owner_compny_lease', views.property_owner_compny_lease, name='property_owner_compny_lease'),
    path('property_lease_payment', views.property_lease_payment, name='lease_payment'),
]
